use_frameworks!

target 'SJSegmented_Example' do
  pod 'SJSegmented', :path => '../'

  target 'SJSegmented_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
